package cz.lastaapps.jetpackreleaseupdater

import java.time.ZoneId
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter

/**
 * Creates Kotlin file with all the libs
 * For customizations, edit options in Main.kt
 * */
fun exportAll(libs: List<Library>): String {

    val date = ZonedDateTime.now(ZoneId.of("UTC"))
        .format(DateTimeFormatter.ISO_OFFSET_DATE)

    //header
    var string =
        """
        |package $packageName
        |
        |/**
        | * This file has been generated by the jetpack-release-updater
        | * https://github.com/Lastaapps/jetpack-release-updater
        | * Generated: $date
        | * ${libs.size} packages
        | * ${libs.map { it.artifacts.size }.sum()} artifacts
        | */
        |object $className {
        |    val data = listOf(
        """.trimMargin()

    //adding the libs
    for (lib in libs) {
        string += "\n" + export(lib)
    }

    //footer
    return """
        |$string
        |    )
        |}
    """.trimMargin()
}

/**
 * Creates representation of one library
 * */
private fun export(lib: Library): String {
    return """
        |        $libClassName(
        |            "${lib.groupIndexUrl}",
        |            "${lib.releasePageUrl}",
        |            "${lib.packageName}",
        |            ${lib.artifactsString()},
        |        ),
    """.trimMargin()
}

/**
 * Creates list of strings
 * @return listOf("art1", "art2", "art3", ...)
 * */
private fun Library.artifactsString(): String {
    var string = "listOf("

    for (art in this.artifacts) {
        string += "\"$art\", "
    }

    string = string.substring(0, string.length - 2)

    return "$string)"
}